[versions]
android-gradle-plugin = "9.0.1"
androidx-activity = "1.12.4"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-documentfile = "1.1.0"
androidx-fragment = "1.8.9"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.4.0"
jgit = "7.5.0.202512021534-r"
json = "20251224"
junit = "1.3.0"
kotlin = "2.3.10"
kotlinx-serialization = "1.10.0"
kudzu = "6.1.0"
libphonenumber = "9.0.24"
material = "1.13.0"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidx-documentfile" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "androidx-preference" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kudzu = { group = "io.github.copper-leaf", name = "kudzu-core", version.ref = "kudzu" }
libphonenumber = { group = "com.googlecode.libphonenumber", name = "libphonenumber", version.ref = "libphonenumber" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Test
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }

# Build script
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
json = { group = "org.json", name = "json", version.ref = "json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
